{% set name = "cuequivariance" %}
{% set version = "0.6.1" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/NVIDIA/cuEquivariance/archive/refs/tags/v{{ version }}.tar.gz
  sha256: c8c3ccf57ff6daf806dfa12d414242cd89135d2ea864d6ef7dbc434f5f992f7a

build:
  noarch: python
  script: {{ PYTHON }} -m pip install ./cuequivariance -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - pip
  run:
    - python >={{ python_min }}
    - numpy
    - scipy
    - opt-einsum
    - sympy
    - networkx

test:
  imports:
    - cuequivariance
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/NVIDIA/cuEquivariance
  summary: CUDA accelerated equivariant operations
  license: Apache-2.0
  license_file: LICENSES/LICENSE

extra:
  recipe-maintainers:
    - fxcoudert
